import { atom } from "nanostores";

export const icons = atom([
    {
        icon:"/tailwind.svg",
        alt:"tailwind"
    },
    {
        icon:"/html.png",
        alt:"HTML"
    },
    {
        icon:"/css.png",
        alt:"CSS"
    },
    {
        icon:"/js.png",
        alt:"javaScript"
    },
    {  
        icon:"/ts.png",
        alt:"typeScript"
    },
    {
        icon:"/react.png",
        alt:"react"
    },
    {
        icon:"/mongodb.png",
        alt:"mongoDB"
    },
    {
        icon:"/nodejs.png",
        alt:"nodeJS"
    },
    {
        icon:"/nextjs.png",
        alt:"nextJS"
    }
])